name: Go CI (Dev Container + Testcontainers)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run build
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Run the devcontainer, with Docker socket mounted
            devcontainer exec \
              --workspace-folder . \
              --docker-host=inherit \
              bash -c "go build -v ./.. "
      - name: Run test
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            # Run the devcontainer, with Docker socket mounted
            devcontainer exec \
              --workspace-folder . \
              --docker-host=inherit \
              bash -c "go test -v ./..."
